### ISSUE TITLE
certs.h Missing

### ISSUE THREAD

**Issue by Eilliar** [MicrochipTech/wcm-aws-iot-sdk#1]
Does not compile because it's missing a certs.h file.
Do you have it or it should use certs_test.h from Harmony?

**Comment by dcmchp** [comment]
The certs.h file must be generated by the user because they are specific to their Amazon Web Services account for this starter kit.

This process is described on the front page here where the source code is located.
https://github.com/MicrochipTech/wcm-aws-iot-sdk

They will have to generate the certificates following the instructions, then convert them to the certs.h file and put them in the appropriate directory.  It should compile after that.

Regards,
David

**Comment by bellhop** [comment]
We did find an issue with our .gitignore file that has been fixed and you should now be able to see the cert folder with the 0.2.1 release.

You will still have to generate your own cert files per the README.md file.

Thank you for the feedback.

**Comment by Eilliar** [comment]
Thanks for all the info.
:+1:

**Comment by Eilliar** [comment]
If I want to connect and send info to a Mosquitto broker (locally installed on a private network machine) it's really necessary to generate certs.h?
I'm just trying to use your code to test WCM Dev Kit 1, and for now I don't really need to send info to a AWS IoT service.

Any ideia on how to do this?

Thanks for now.

^^

**Comment by bellhop** [comment]
You could setup your own MQTT broker using Mosquitto.  Here is a link to the MQTT page that talk about how to do this: [link](https://github.com/mqtt/mqtt.github.io/wiki/Mosquitto-Message-Broker)

How you setup the service will depend on if you need certs or not; but we have not tested this as we just used Mosquitto to verify that we had access to the AWS IoT service.

**Comment by Eilliar** [comment]
Sorry to bother, but I'm really new to that. Aparrently the board is successfully connecting to my WiFi network, but it's seems that it's not able to connect to the Mosquitto broker. I'm currently using certification (keys and CA)  and I've created my own "certs.h" with all those info (certificates as strings). 
I'm looking into your code and I can´t see a option to "turno off " the use of certification on my connection. Is it possible to do so?
Can you give me some light on wich part of your code I've to look for this?
I'm just trying to run a demo on a local network and I don't need to use SSL/TLS for now.

Again, thanks for your help.

**Comment by dcmchp** [comment]
To disable SSL authentication you simply need to change the socket options in the presentation layer.
Look for the NET_PRES_SKT_Open() function in ``app.c'' and change the the socket type to NET_PRES_SKT_UNENCRYPTED_STREAM_CLIENT.  This should be a typical TCP stream now.

Then just ensure you have the correct host/port set for your local broker, this can be found in APP_Initialize().  

I tested this by connecting to the public ``test.mosquitto.com'' on port ``1883'' server and published some data from the starter kit.  It worked!

Good luck.

**Comment by Eilliar** [comment]
Hi, I managed to acquire a AWS account and run AWS IoT. It's up and running now!

Thank you for all your help.

;)
