### ISSUE TITLE
D1, D3, D5 and D6 continuously ON after configuring AWS IoT end-point and local WiFi Access Point

### ISSUE THREAD

**Issue by dotrc** [MicrochipTech/wcm-aws-iot-sdk#2]
Hi,

Following the instructions in the README here, I was able to compile and deploy the firmware on WCM 1 board. Prior to upgrade, I could see the old EC2 instance based interface on 192.168.1.25. Post upgrade, I can see the new interface at 192.168.1.1.

However, I am not able to connect to the device from AWS IoT. The device (instead of blinking D6) shows D1, D3 (both green) and D5 and D6 (both blue) continuously ON after initial D1 - D4 circular blinking.
I have followed the instructions given at https://github.com/MicrochipTech/wcm-aws-iot-sdk

What could have gone wrong? I have a reference doc for WCM 1 board for legacy EC2 based IoT support (www.farnell.com/datasheets/1889905.pdf), but not sure if the LED Diagnostic report holds good now.

Thanks!

**Comment by dcmchp** [comment]
Hi dotrc,

This is generally one of two issues:
1.  Double check that the AWS IoT endpoint issued to your account is being entered correctly.  If the endpoint is wrong, it won't resolve the DNS correctly.

2.  Double check that the access point you have the starter kit connecting to has an active internet connection.

**Comment by bellhop** [comment]
We will be adding this to the README.md doc very soon, but in the meantime, here is the updated chart for this project.

##### Status and Error Code Table
 D7  | D6  | D5  | D4  | D3  | D2  | D1  | Diagnostic Report
:---:|:---:|:---:|:---:|:---:|:---:|:---:|-----
 -   | 0   | F   | 0   | 0   | 0   | 0   | Configuration Mode: Need to configure Connected to AP
 -   | F   | F   | 0   | 0   | 0   | 0   | Connected to AP and waiting on data
 -   | 1   | 0   | C   | C   | C   | C   | Associating to AP
 -   | 1   | 1   | 0   | 0   | 0   | 1   | Connection Issue, no internet found
 -   | 1   | 1   | 0   | 0   | 1   | 0   | Association to AP failed
 -   | 1   | 1   | 0   | 1   | 0   | 1   | DNS Unresolved: Bad endpoint or no connection
 -   | F   | 0   | -   | -   | -   | -   | Normal Operation: D6 flashes each message transmission
 -   | 0   | F   | -   | -   | -   | -   | Normal Operation: D5 flashes each subscription receive
 1   | -   | -   | -   | -   | -   | -   | Battery Voltage Low
F = Flashing, C = Rotating in a counter clockwise pattern, - = Don’t care, 0 = Off, and 1 = On

**Comment by dotrc** [comment]
Hi bellhop,

Thanks for sharing the new debug matrix. This helped me a lot, the local issue found and resolved.
Looking forward to have this matrix appended to README :)
